package eva;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Clase F2 que muestra las conversaciones almacenadas.
 */
public class F2 extends javax.swing.JFrame {

    private DefaultListModel<String> listModel;
    private String[][] conversaciones;

    // Constructor que acepta la matriz de conversaciones
    public F2(String[][] conversaciones) {
        this.conversaciones = conversaciones; // Almacena la matriz de conversaciones
        initComponents();
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        // Cargar las conversaciones en el JList
        cargarConversaciones();
    }

    // Método que carga las conversaciones en el JList
    private void cargarConversaciones() {
        for (int i = 0; i < conversaciones.length; i++) {
            if (conversaciones[i][0] != null) { // Si hay una conversación en esa fila
                listModel.addElement("chat # " + (i + 1));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnatrásinicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnatrásinicio1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 290, 160));

        btnatrásinicio.setBackground(new java.awt.Color(240, 215, 92));
        btnatrásinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eva/back.png"))); // NOI18N
        btnatrásinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatrásinicioMouseClicked(evt);
            }
        });
        btnatrásinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrásinicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnatrásinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jLabel2.setBackground(new java.awt.Color(240, 215, 92));
        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Historial");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 40));

        btnatrásinicio1.setBackground(new java.awt.Color(240, 215, 92));
        btnatrásinicio1.setText("🠠");
        btnatrásinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatrásinicio1MouseClicked(evt);
            }
        });
        jPanel1.add(btnatrásinicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnSalir.setBackground(new java.awt.Color(240, 215, 92));
        btnSalir.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 170, 30));

        btnir.setBackground(new java.awt.Color(240, 215, 92));
        btnir.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnir.setText("Ir al chat ");
        btnir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnirMouseClicked(evt);
            }
        });
        btnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirActionPerformed(evt);
            }
        });
        jPanel1.add(btnir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 160, 30));

        btnNuevo.setBackground(new java.awt.Color(240, 215, 92));
        btnNuevo.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eva/plus24.png"))); // NOI18N
        btnNuevo.setText("Nuevo chat");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrásinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatrásinicioMouseClicked
        F1 frame = new F1(); // Crea una nueva instancia de F2
        frame.setVisible(true); // Hace visible el JFrame F2
        frame.setLocationRelativeTo(null); // Centra el JFrame F2 en la pantalla
        dispose();
    }//GEN-LAST:event_btnatrásinicioMouseClicked

    private void btnatrásinicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatrásinicio1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrásinicio1MouseClicked

    private void btnatrásinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrásinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrásinicioActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar el programa");
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
  
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Crea una matriz de conversaciones de ejemplo
                String[][] conversaciones = new String[10][2];
                conversaciones[0][0] = "Hola"; // Agrega una conversación de ejemplo

                // Pasa la matriz de conversaciones al constructor de F2
                new F2(conversaciones).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnatrásinicio;
    private javax.swing.JButton btnatrásinicio1;
    private javax.swing.JButton btnir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
